# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='boundaryConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physicalGroup', models.CharField(max_length=100, verbose_name='physicalgroup')),
                ('bcType', models.CharField(max_length=100, verbose_name='bcType')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Simulation', verbose_name='relatedSimulation')),
            ],
        ),
    ]
