# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='materialChoice',
            field=models.CharField(choices=[('a', 'a'), ('a', 'b'), ('a', 'c')], max_length=100, verbose_name='materialtypes'),
        ),
    ]
