# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170218_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='conductivity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='conductivity'),
        ),
        migrations.AddField(
            model_name='materials',
            name='density',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='density'),
        ),
        migrations.AddField(
            model_name='materials',
            name='heatCapacity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='heatCapacity'),
        ),
        migrations.AddField(
            model_name='materials',
            name='poissonRatio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='poissonRatio'),
        ),
        migrations.AddField(
            model_name='materials',
            name='viscosity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Viscosity'),
        ),
        migrations.AddField(
            model_name='materials',
            name='youngsModulus',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='youngsModulus'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='timeFlag',
            field=models.BooleanField(default=True, verbose_name='timeFlag'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='materialChoice',
            field=models.CharField(choices=[('Elastic', 'Elastic'), ('Heat', 'Heat'), ('Fluid', 'Fluid')], max_length=100, verbose_name='materialtypes'),
        ),
    ]
